version: 1.0.{build}
image: Visual Studio 2019
environment:
  matrix:
  - arch: x64
clone_folder: c:\solc-build
cache:
- C:\solc-build\boost_1_77_0-msvc-14.1-64.exe
branches:
  only:
    - master
skip_tags: true

before_build:
  - git submodule update --init --recursive || exit

build_script:
  - build-win.bat %arch% Release || exit
  - 7z a win-%arch%.zip %APPVEYOR_BUILD_FOLDER%/solidity/build-Release-x%arch%/libsolc/Release/solc.dll || exit
  - appveyor PushArtifact win-%arch%.zip